--Q8
SELECT E_NAME as owner_name,PHONE as owner_phone
FROM PERSON
WHERE Owner_ID IN (
SELECT OWNER_ID
FROM OWNS
WHERE Pdate >= DATEADD(MONTH, -1, CAST(GETDATE() AS date)))
UNION
SELECT C_NAME,CPHONE
FROM CORPORATION
WHERE Owner_ID IN (
SELECT OWNER_ID
FROM OWNS
WHERE Pdate >= DATEADD(MONTH, -1, CAST(GETDATE() AS date)))